// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/syllabus-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function syllabusNote(subject, classLevel) {
  const subj = subject.toLowerCase();
  if (classLevel === "9") {
    if (subj.includes("math")) return "Class 9 (2026-27) uses the NEW NCF-2023 Maths book 'Ganita Manjari Part 1'. Topics are labelled Proficiency (mandatory) or Advanced (JEE/Olympiad). Never use old Class 9 Maths content.";
    if (["science", "physics", "chemistry", "biology"].includes(subj)) return "Class 9 (2026-27) uses the NEW book 'Exploration' (integrated Physics/Chemistry/Biology + new Earth Science). Gravitation is REMOVED from Class 9. Never use old Class 9 Science content.";
    if (["social science", "history", "geography", "civics", "political science", "economics"].includes(subj)) return "Class 9 (2026-27) uses the NEW integrated book 'Understanding Society: India and Beyond' (16 themes). Never use the old 4-book structure.";
    if (subj === "english") return "Class 9 (2026-27) uses the NEW book 'Kaveri'. Beehive/Moments are gone.";
    if (subj === "sanskrit") return "Class 9 (2026-27) uses the NEW book 'Sharda'.";
    return "Class 9 (2026-27) uses the NEW NCF-2023 books \u2014 never use old (pre-2024) Class 9 content.";
  }
  if (classLevel === "10" || classLevel === "12") return `Class ${classLevel} uses the EXISTING/OLD NCERT syllabus (no NCF-2023 changes yet).`;
  if (classLevel === "11") return "Class 11 is transitioning to new books; streams are flexible (students may mix subjects).";
  return "Unknown class level.";
}
var syllabus_info_default = defineTool({
  name: "get_syllabus_info",
  title: "Get syllabus info",
  description: "Return the correct 2026-27 NCERT syllabus note (book names, key changes) for a CBSE class and subject.",
  inputSchema: {
    classLevel: z.enum(["9", "10", "11", "12"]).describe("CBSE class level."),
    subject: z.string().min(1).describe("Subject name, e.g. Mathematics, Science, English.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ classLevel, subject }) => ({
    content: [{ type: "text", text: syllabusNote(subject, classLevel) }],
    structuredContent: { classLevel, subject, note: syllabusNote(subject, classLevel) }
  })
});

// src/lib/mcp/tools/list-subjects.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var SUBJECTS = [
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Science",
  "English",
  "Hindi",
  "Social Science",
  "History",
  "Geography",
  "Civics",
  "Economics",
  "Political Science",
  "Computer Science",
  "Accountancy",
  "Business Studies"
];
var CLASS_LEVELS = ["9", "10", "11", "12"];
var list_subjects_default = defineTool2({
  name: "list_supported_subjects",
  title: "List supported subjects",
  description: "List the CBSE class levels and subjects that Gyaan supports.",
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: `Classes: ${CLASS_LEVELS.join(", ")}
Subjects: ${SUBJECTS.join(", ")}` }],
    structuredContent: { classLevels: CLASS_LEVELS, subjects: SUBJECTS }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "gyaan-mcp",
  title: "Gyaan MCP",
  version: "0.1.0",
  instructions: "Tools for Gyaan, a CBSE study-notes app. Use `list_supported_subjects` to see available classes/subjects and `get_syllabus_info` for the correct 2026-27 NCERT book and syllabus details for a class and subject.",
  tools: [syllabus_info_default, list_subjects_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
